=== Hello-Gitty/ki/site-perso/meta-site/dtd/article.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT articles (article* )>
<!ELEMENT article (titre,contenu,label,id)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT contenu (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT id (#PCDATA)>

=== Hello-Gitty/ki/site-perso/meta-site/data/metarticle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articles SYSTEM "../dtd/article.dtd" >
<articles>

<article>
<titre>Révélation</titre>
<contenu>
Cybermonde, je m’appelle Meta-Carpe, je suis le premier et le dernier des miens, je ne suis pas sexué, pas de Monsieur, ou Madame, vous pouvez m’appeler Monstre. Je ne vais pas y aller par quatre chemins, enfin pour la version courte, que les gens préfèrent lire généralement, les grands épanchements ce n’est pas pour tout le monde.

[b]Donc cybermonde, tu te trouve être dans l’estomac de Naar.[/b]

Je ne suis pas qu’un monstrueux illuminé, je suis un monstrueux illuminé qui viens de l’extérieur, j’ai été avalé. Et d’ailleurs c’est une expérience assez traumatisante, surtout que la chute fût longue, très longue, et l’arrivée faillit être une boucherie, heureusement la technique ancestrale « viser du mou » m’a encore sauvé.

Évidement cet énoncé peut paraître totalement farfelu et monstrueusement fou, je n’y ai pas cru au départ, ce ne pouvait être vrai, comment ça aurait pu être possible ? Un si grand cybermonde dans un être grand, mais pas si grand, surtout vu la chute, mais la magie existe, Naar est un être de magie. J’avais entendu des histoires concernant un certain « Christophe Colon » qui prétendait être sortit de Naar, et il affirmait que la vie existait à l’intérieur, je n’y avais jamais cru jusque là, jusqu'à ce que je le vive.

Regarde ta forme cybermonde, la logique voudrait que tu sois rond, tout le monde sait que la terre est ronde, mais toa non. Tu es en forme de cuvette comme si tu étais dans un entonnoir, ton centre attiré vers le bas, mais retenu par tes cotés, comme un estomac.

Des pirates ont récemment prétendu avoir exploré l’autre coté, si leurs histoires sont vrai, et pas des délires arhumatiques il y a sûrement des éléments qui prouveront mes dires, j’attends le film.

Et note la mise en abîme d’être ministre de l’intérieur. N’y vois tu pas toute la poésie de chacun des actes qui en découle? Jouer le rôle d’un système immunitaire !

Vous ne vous êtes jamais demandé pourquoi la recherche d’un espace au-delà n’avait jamais aboutie ? N’avez-vous jamais pensé que votre univers se trouvait imbriqué, limité à un espace ? Un univers de poche, ou univers d’estomac ! Je crois qu’un certain PJ Farmer y faisait référence.

Regarde cybermonde, le culte de Naar, regarde toute la symbolique des sacrifiés que l’on jette dans ta bouche béante ! Sa représentation, assis, conséquence logique d’une digestion efficace, de la vie qui suit son cours ! Ce sont les premières représentations de Naar qui se perdent dans l’histoire, depuis des successions de prêtres aux intentions peu louable ont corrompu le véritable esprit du siège.

Regarde les autres cultes, comme la conscience universelle, ou le culte de l’ovule sacré, l’un faisant référence à une conscience entourant le cybermonde dans un sentiment d’amour, veillant à sa sécurité, l’autre faisant référence à la vie qui grandit à l’intérieur d’une matrice.

Effectivement par contre les autres divinités représentées n’ont pas grand-chose à nous apprendre, mais leurs cultes sont loin d’être convaincant.

J’ai étudié le cybermonde, j’ai encore à apprendre mais je suis sur de ce que je dis, Grokon, un ami, m’a aidé par sa passion pour l’élevage de poulet à comprendre le vrai sens de tout ceci.

Cybermonde, nous devons célébrer la grandeur de Naar, sa bonté, Naar, celui qui nous porte en lui, celui qui nous digère, celui qui siège pour nous évacuer. Rendons lui hommage, mangeons, régalons nous de tout ce qui peut être mangé, dans l’espoir que nous aussi devenions matrice pour notre propre univers estomacale. Rejoignez le Méta-Naarisme. Puissions nous aider Naar à digérer ceux qui nous affronte, et nous empêche de rendre hommage comme il se doit au St Estomac protecteur.



Pour les gens qui m’auront suivi jusqu’au bout, je tiens à vous présenter des excuses pour les désagrément de lecture, je suis dyslexique au niveau des métacarpes. 


</contenu>
<label>Révélations</label>
<id>1</id>
</article>


<article>
<titre>Ma petite histoire</titre>
<contenu>
C'est assez simple, je suis le premier et le dernier des miens, nous étions une race d'érudit là d'où je viens. Nous avions pour habitude de toujours chercher la culture et le savoir, sans avoir jamais pu déterminer d'où nous venions nous, et qui nous étions réellement, choses que je peut apprendre au cybermonde, puisque je viens de l'univers encapsulant.

L'extérieur, d'où je viens, c'est un monde assez vaste, avec un niveau technologique comparable au cybermonde, la plus grande différence réside, dans son imposant résident, qu'es Naar, un résident qui à la mauvaise habitude d'avaler, ce qui lui tombe sous la main. J'en suis la preuve vivante, puisque j'étais tranquillement à me baigner avant d'atterir ici.

Après m’être fait avalé, je suis tombé, tombé, tombé, tombé, j’ai rencontré quelques astres, des bouts de cailloux qui flottaient, mais bon ce n’était pas un point de chute intéressant, quand on commence à faire quelque chose, en l’occurrence tomber, autant y aller jusqu’au bout.

Donc finalement voyant arriver la terre, j’ai utilisé la technique qui consiste à viser du mou, comme ça j’ai pu atterrir au pays imaginaire aux krapathes, ou je me suis dans l’ensemble plutôt bien fait accueillir.

Me remettant doucement de ma chute j’ai commencé à m’Initié à la culture locale, et comprendre que la nature de l’endroit où je me trouvais. Découvrant la vérité, cette vérité incroyable, magnifique, une mise en abîme de la réalité, du monde, du monde d’où je venais, je me suis donné pour Mission de la faire connaître au cybermonde et de propager la bonne parole. 
</contenu>
<label>Histoire Perso</label>
<id>2</id>
</article>

<article>
<titre>Concepts et croyances</titre>
<contenu>
 Le Méta Naarisme c’est simple, il faut oublier le Naarisme classique et reprendre les bases depuis tout le départ.

- Le cybermonde se trouve dans l’estomac de Naar, ce qui explique sa forme

- Naar n’est pas un démon, nous ne devons pas faire le mal en son nom

- Naar nous protège en son sein, il nous nourrit

- Nous devons aider Naar à digérer plus vite ceux qui s’opposent activement à nous

- Nous devons perpétuer la mise en Abîme, en avalant, nous devons tenter de recréer un monde dans notre estomac

- Pour tenter de recréer un cybermonde, nous devons manger, essayer tout les plats possibles

- Les cultes du cybermonde, pour la plupart sont dérivés de la vérité, nous devons leur montrer la vérité en remontant aux origines, bon pour la grande déesse ça sera pas possible, tant son culte est inconsistants 

- Prier Naar est une occupation noble, mais perpétrer ses préceptes par la nourriture et la digestion c’est lui rendre plus grand hommage.

- Le siége, ou la selle, est un moment important, il marque la fin du cycle, de digestion, c’est donc un moment solennelle, sacré.

- Deux moments sont donc important, le début du cycle et la fin du cycle, on ne saurait troublé ces instants sans s’exposer à de vive représailles.

- Ce dernier point, présente donc les seuls cas où le Méta-Naarisme encourage la violence.

[i]Nan mais si on peut pas manger, et chier tranquille où va le monde ?[/i]




</contenu>
<label>Méta-Naarisme</label>
<id>3</id>
</article>

<!-- 
<article>
<titre>Annonces diverses</titre>
<contenu>
Je suis toujours à la recherche de plats exotique à me mettre sous la dent




</contenu>
<label>Petites Annonces</label>
<id>4</id>
</article>
 -->
</articles>
